package com.simorgh.mac.str

// Generated from values/strings.xml (EN) and values-fa/strings.xml (FA) by tools/gen_strings.py.
import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import com.simorgh.mac.model.AppLanguage
import java.util.Locale

object Strings {
    val EN: Map<String, String> = mapOf(
        "action_add" to "Add",
        "action_back" to "Back",
        "action_cancel" to "Cancel",
        "action_clear" to "Clear",
        "action_close" to "Close",
        "action_collapse" to "Hide servers",
        "action_connect" to "Connect",
        "action_copy_link" to "Copy link",
        "action_copy_value" to "Copy %1\$s",
        "action_delete" to "Delete",
        "action_details" to "Details",
        "action_expand" to "Show servers",
        "action_favorite" to "Add to favourites",
        "action_find_servers" to "Find servers",
        "action_grant_permission" to "Allow VPN",
        "action_hide_qr" to "Hide QR code",
        "action_paste" to "Paste",
        "action_refresh_servers" to "Refresh servers",
        "action_remove_subscription" to "Remove %1\$s",
        "action_save" to "Save",
        "action_share" to "Show QR code",
        "action_test" to "Test",
        "action_test_servers" to "Test servers",
        "action_try_again" to "Try again",
        "action_unfavorite" to "Remove from favourites",
        "ago_days" to "%1\$s d ago",
        "ago_hours" to "%1\$s h ago",
        "ago_minutes" to "%1\$s min ago",
        "ago_never" to "Never",
        "ago_now" to "Just now",
        "app_name" to "ZeroNet",
        "apps_body_except" to "The apps you tick skip the VPN.",
        "apps_body_only" to "Only the apps you tick use the VPN.",
        "apps_search" to "Search apps",
        "badge_skipped" to "Skipped",
        "brand_name" to "ZeroNet",
        "cdn_blocked" to "Cloudflare CDN configs don't work on this network, so they're skipped.",
        "cdn_throttled_ech" to "Cloudflare is throttled on this network; hiding the server name to get through.",
        "cdn_throttled_split" to "Cloudflare is throttled on this network; splitting the handshake to get through.",
        "clear_history_nothing" to "There are no discovered servers to clear.",
        "countries_search" to "Search countries",
        "country_unknown" to "Unknown location",
        "delay_failed" to "Failed",
        "delay_ms" to "%1\$s ms",
        "delay_unknown" to "—",
        "detail_address" to "Address",
        "detail_auto_select" to "Use for automatic picks",
        "detail_auto_select_hint" to "Off: auto-connect and switching skip this server. You can still tap it to connect.",
        "detail_delay" to "Delay",
        "detail_delete_confirm" to "Delete this server? This can’t be undone.",
        "detail_error" to "Why it failed",
        "detail_history" to "Success rate",
        "detail_history_value" to "%1\$s of %2\$s tests",
        "detail_last_tested" to "Last tested",
        "detail_protocol" to "Protocol",
        "detail_qr_description" to "QR code with this server’s link",
        "detail_security" to "Security",
        "detail_share_warning" to "Anyone with this code can use the server. Share it only with people you trust.",
        "detail_source" to "Source",
        "detail_testing" to "Testing…",
        "detail_transport" to "Transport",
        "diag_body" to "Checks your network outside the tunnel, then tries a few saved servers of every kind.",
        "diag_dns" to "DNS (filtered sites)",
        "diag_family" to "Servers: %1\$s",
        "diag_internet" to "Plain internet",
        "diag_network" to "Network",
        "diag_not_run" to "Not run yet.",
        "diag_run" to "Run test",
        "diag_run_again" to "Run again",
        "diag_status_bad" to "Blocked",
        "diag_status_ok" to "Works",
        "diag_status_pending" to "Waiting",
        "diag_status_running" to "Testing…",
        "diag_status_skipped" to "Skipped",
        "diag_status_warn" to "Partly",
        "diag_title" to "Connection test",
        "diag_tls" to "TLS server names (DPI)",
        "diag_tunnel" to "Through the tunnel",
        "diag_verdict_families" to "Right now these kinds get through: %1\$s. ZeroNet prefers them automatically.",
        "diag_verdict_no_internet" to "This network does not reach the internet at all, and no server answered.",
        "diag_verdict_no_servers" to "No saved servers to test yet. Connect once (or refresh the server list) and run the test again.",
        "diag_verdict_none_work" to "None of the saved servers answered. Refresh the server list, try the clean-IP scanner, or add a config of your own.",
        "diag_verdict_offline" to "There is no network. Connect to Wi-Fi or mobile data first.",
        "fail_core" to "Couldn’t start the connection. Try again.",
        "fail_no_network" to "You’re offline. Check Wi-Fi or mobile data.",
        "fail_no_server" to "No working server found on this network. Try again in a minute, or set Anti-censorship to Strong.",
        "fail_server_unavailable" to "That server isn’t answering. Try the fastest one instead.",
        "fail_vpn_permission" to "ZeroNet needs permission to set up a VPN.",
        "fail_vpn_revoked" to "Another VPN app took over.",
        "gaming_on_note" to "Best ping, less security: weaker servers and UDP are allowed.",
        "gaming_on_title" to "Gaming mode on",
        "gaming_ping" to "PING %1\$s ms",
        "gaming_title" to "GAME MODE",
        "import_body" to "Paste one or more config links, or a subscription link.",
        "import_error" to "Couldn’t import: %1\$s",
        "import_links" to "Links",
        "import_links_placeholder" to "vless://, vmess://, trojan://, ss://…",
        "import_result" to "Added %1\$s · %2\$s already here · %3\$s not recognised",
        "import_sub_hint" to "ZeroNet refreshes it together with the public lists.",
        "import_sub_invalid" to "Enter an address that starts with https://",
        "import_sub_name" to "Name (optional)",
        "import_sub_url" to "https://…",
        "import_subscription" to "Subscription",
        "import_title" to "Add configs",
        "kind_cdn" to "CDN",
        "kind_crowd" to "Works for others",
        "kind_direct" to "Direct",
        "kind_hint_cdn" to "Behind a CDN such as Cloudflare: blocking it would block much of the web.",
        "kind_hint_crowd" to "Other ZeroNet users reported this server working on their networks.",
        "kind_hint_direct" to "REALITY: looks like a visit to a real, unfiltered website.",
        "kind_hint_other" to "A plain config without disguise: works only where it is not filtered yet.",
        "kind_hint_quic" to "Hysteria2 or TUIC over UDP: fast when UDP gets through, useless when it does not.",
        "kind_hint_split" to "XHTTP with separate upload and download paths: the hardest kind for filters to recognise.",
        "kind_other" to "Standard",
        "kind_quic" to "QUIC",
        "kind_split" to "Split path",
        "kw_about" to "version licence license source code open source engine zray update upgrade new",
        "kw_appearance" to "theme colour color dark light amoled black language persian english farsi animation motion",
        "kw_connection" to "vpn proxy auto connect reconnect always-on kill switch lockdown mtu ipv6 network",
        "kw_diagnostics" to "diagnostics test troubleshoot logs debug problem not working dpi dns",
        "kw_evasion" to "censorship filtering fragment dpi sni dns doh quic ads adblock tracker",
        "kw_privacy" to "logs history delete clear data privacy share anonymous crowd others help",
        "kw_share" to "share lan wifi hotspot tether socks http proxy port qr password",
        "kw_sources" to "sources subscription feed list github country countries refresh update",
        "kw_split" to "split bypass per-app apps exclude route routing iran local lan",
        "licences_body" to "ZeroNet is built on these projects.",
        "logs_body" to "The connection log records what ZeroNet tried. Turn on detailed logs in Privacy for more from the core.",
        "logs_body_detailed" to "Detailed logs are on. Share these when asking for help; they hold server names and errors, not the sites you visit.",
        "logs_clear" to "Clear",
        "logs_connection" to "Connection",
        "logs_copy" to "Copy",
        "logs_core" to "Core",
        "logs_empty" to "Nothing logged yet.",
        "logs_refresh" to "Refresh",
        "logs_share" to "Share",
        "logs_title" to "Logs",
        "mars_words" to "Connecting from Mars, might take a moment",
        "msg_copied" to "Copied",
        "msg_deleted" to "Server deleted",
        "msg_history_cleared" to "Discovered servers cleared",
        "msg_subscription_added" to "Subscription added. Fetching its servers…",
        "msg_vpn_permission_denied" to "ZeroNet can’t connect without VPN permission",
        "notification_blocked_detail" to "Kill switch: apps are offline until a server works",
        "notification_channel" to "Connection status",
        "notification_connected" to "Connected",
        "notification_connecting" to "Connecting…",
        "notification_disconnect" to "Disconnect",
        "notification_reconnecting" to "Reconnecting…",
        "notification_searching" to "Finding a server…",
        "notification_searching_detail" to "Tested %1\$d · %2\$d working",
        "notification_server_ping" to "%1\$s · %2\$d ms",
        "notification_switch" to "Switch server",
        "onboarding_allow" to "Allow",
        "onboarding_later" to "Not now",
        "onboarding_perm_text" to "VPN, so your apps' traffic can go through the tunnel, and notifications, so you can see whether you're connected. Android asks for each once, and you can change them later in system settings.",
        "onboarding_perm_title" to "ZeroNet needs two permissions",
        "option_auto" to "Auto",
        "option_off" to "Off",
        "option_system" to "System",
        "orb_action_connect" to "Connect",
        "orb_action_disconnect" to "Disconnect",
        "orb_connect" to "CONNECT",
        "orb_connected" to "CONNECTED",
        "orb_connecting" to "CONNECTING",
        "orb_disconnecting" to "STOPPING",
        "orb_failed" to "RETRY",
        "palette_arctic" to "Arctic",
        "palette_contrast" to "Contrast",
        "palette_golden" to "Golden",
        "palette_nightshade" to "Nightshade",
        "palette_paper" to "Paper",
        "palette_sakura" to "Sakura",
        "path_dns" to "Your provider gives fake answers for blocked sites.",
        "path_do_dns" to "ZeroNet uses its own DNS inside the tunnel, so this does not stop it.",
        "path_do_offline" to "Connect to a network that has internet, then run the test again.",
        "path_do_redirect" to "Open your browser once to check for a login page, then run the test again.",
        "path_do_sni" to "ZeroNet prefers servers that hide the name, so they still get through.",
        "path_filter" to "The filter",
        "path_hint_idle" to "Run the test to see where your connection gets stopped.",
        "path_no_internet" to "This network does not let traffic through to the internet.",
        "path_no_network" to "Your phone has no network.",
        "path_no_server" to "No saved server got through right now.",
        "path_ok_all" to "Nothing is blocking you right now.",
        "path_phone" to "Your phone",
        "path_provider" to "Your provider",
        "path_redirected" to "Something on this network redirects your traffic, like a login page or a filter.",
        "path_running" to "Checking each step of the way…",
        "path_sni" to "The filter reads site names in secure connections and cuts the ones it dislikes.",
        "path_world" to "Open internet",
        "picker_countries" to "Countries",
        "picker_empty" to "No servers yet. Connect once and ZeroNet will find some.",
        "picker_favorites" to "Favourites",
        "picker_mine" to "Your configs",
        "picker_subscriptions" to "Your subscriptions",
        "picker_title" to "Choose a server",
        "profile_fast" to "Fast",
        "profile_fast_hint" to "Connects to the first server that works",
        "profile_gaming" to "Gaming",
        "profile_gaming_hint" to "Best ping, less security: weaker servers and UDP are allowed, and it never switches mid-game",
        "profile_legacy" to "Legacy",
        "profile_legacy_hint" to "How Normal worked before: encrypted servers, one search",
        "profile_normal" to "Normal",
        "profile_normal_hint" to "Recommended. Encrypted servers with backups, and it keeps trying other ways until one connects",
        "profile_tag_fast" to "Quickest",
        "profile_tag_gaming" to "Low ping",
        "profile_tag_legacy" to "Classic",
        "profile_tag_normal" to "Recommended",
        "race_blocked" to "Blocked",
        "race_connected" to "Connected · %1\$s s",
        "race_failed" to "None of the ways got through. Try another network, or another account.",
        "race_failed_short" to "Failed",
        "race_h2" to "Web (HTTP/2)",
        "race_h3" to "QUIC (HTTP/3)",
        "race_live" to "Trying %1\$d ways to reach Cloudflare at once…",
        "race_no_answer" to "No answer",
        "race_no_traffic" to "Nothing got through",
        "race_not_needed" to "Not needed",
        "race_title" to "How it connected",
        "race_trying" to "Trying…",
        "race_waiting" to "Waiting",
        "race_wireguard" to "WireGuard",
        "race_won_blocked" to "Connected through %1\$s. The network blocked the other ways, so the app used the one that works here.",
        "race_won_fastest" to "Connected through %1\$s, the fastest way right now.",
        "scan_from_photo" to "From a photo",
        "scan_hint" to "Point the camera at a config or subscription QR code.",
        "scan_no_camera" to "No camera access. You can still pick a photo or screenshot of the code.",
        "scan_not_found" to "No QR code found in that picture.",
        "scan_qr" to "Scan a QR code",
        "scanner_again" to "Scan again",
        "scanner_best" to "Best",
        "scanner_copy_best" to "Copy top %1\$s",
        "scanner_copy_ip" to "Copy %1\$s",
        "scanner_done" to "Finished",
        "scanner_error_title" to "The scan stopped",
        "scanner_explainer" to "Find Cloudflare addresses that still answer on your network",
        "scanner_how_body" to "Many servers sit behind Cloudflare. When its usual IPs are blocked, a clean IP that still works on your ISP gets them working again. ZeroNet uses the best results automatically.",
        "scanner_how_title" to "Why scan?",
        "scanner_idle_hint" to "About a minute",
        "scanner_none_found" to "No address answered this time. Try again later or on another network.",
        "scanner_port" to "Port %1\$s",
        "scanner_progress_description" to "Scan progress",
        "scanner_progress_state" to "%1\$s percent",
        "scanner_ready" to "Ready",
        "scanner_responsive" to "Answered",
        "scanner_results" to "Fastest addresses",
        "scanner_scanned" to "Scanned",
        "scanner_scanning" to "Scanning…",
        "scanner_start" to "Start scan",
        "scanner_stop" to "Stop",
        "server_card_action" to "Choose a server",
        "server_country_best" to "Best server in this country",
        "server_fastest" to "Fastest server",
        "server_fastest_hint" to "ZeroNet picks it for you",
        "server_fastest_picked" to "Fastest",
        "server_subscription_hint" to "Switches only between this subscription's configs",
        "servers_add_body" to "Config links or a subscription link",
        "servers_add_title" to "Add configs",
        "servers_countries" to "Countries",
        "servers_empty_body" to "Tap Find servers. ZeroNet downloads public lists and tests them on your connection.",
        "servers_empty_title" to "No servers yet",
        "servers_finding" to "Searching…",
        "servers_mine" to "Mine",
        "servers_mine_empty_body" to "Paste a config link or a subscription link.",
        "servers_mine_empty_title" to "Nothing added yet",
        "servers_no_matches" to "Nothing matches “%1\$s”",
        "servers_rec_empty_body" to "Test the list to see which servers work on your connection.",
        "servers_rec_empty_title" to "No tested servers yet",
        "servers_recommended" to "Recommended",
        "servers_search" to "Search a country or name",
        "servers_subscriptions" to "Subscriptions",
        "servers_subtitle_empty" to "Nothing found yet",
        "servers_testing" to "Testing %1\$s of %2\$s…",
        "servers_working_count" to "%1\$s working",
        "servers_your_servers" to "Your configs",
        "settings_about" to "About",
        "settings_amoled" to "Pure black",
        "settings_amoled_hint" to "Saves power on OLED screens",
        "settings_anti_sanction" to "DNS for sanctioned services",
        "settings_anti_sanction_hint" to "Sites that block Iranian IPs (OpenAI, GitHub, …) are looked up here and reached directly",
        "settings_anti_sanction_note" to "Leave empty to use a provider above. Accepts an IP or an IP-addressed tls://… / https://…/dns-query.",
        "settings_appearance" to "Appearance",
        "settings_applies_next" to "Applies on next connect",
        "settings_apps" to "Apps",
        "settings_apps_all" to "All",
        "settings_apps_except" to "All but chosen",
        "settings_apps_none" to "None chosen",
        "settings_apps_only" to "Only chosen",
        "settings_apps_proxy_note" to "Only applies in VPN mode",
        "settings_autoconnect" to "Connect automatically",
        "settings_autoconnect_app" to "App opens",
        "settings_autoconnect_boot" to "Phone starts",
        "settings_autoswitch" to "Switch to a faster server",
        "settings_autoswitch_hint" to "When the current one slows down or drops",
        "settings_block_ads" to "Block ads and trackers",
        "settings_block_ads_hint" to "Filters known ad domains for every app",
        "settings_block_quic" to "Block QUIC",
        "settings_block_quic_hint" to "Apps fall back to TCP instead of stalling",
        "settings_bypass_lan" to "Local network skips the VPN",
        "settings_bypass_lan_hint" to "Printers, TVs and your router stay reachable",
        "settings_choose_apps" to "Choose apps",
        "settings_clear_history" to "Clear discovered servers",
        "settings_clear_history_hint" to "Forget public servers and test results. Servers you added stay.",
        "settings_connection" to "Connection",
        "settings_custom_dns_hint" to "Custom resolver (e.g. 8.8.8.8)",
        "settings_custom_dns_note" to "Leave empty to use a provider above. Accepts an IP, tls://…, or https://…/dns-query.",
        "settings_diag_logs" to "View logs",
        "settings_diag_logs_hint" to "What ZeroNet tried, what answered and why things failed",
        "settings_diag_test" to "Test my connection",
        "settings_diag_test_hint" to "Find out what your network blocks and which kinds of server get through",
        "settings_diagnostics" to "Diagnostics",
        "settings_dynamic" to "Wallpaper colours",
        "settings_dynamic_hint" to "Material You colours from your wallpaper",
        "settings_engine" to "Engine",
        "settings_engine_hint" to "The open-source core that runs the connection",
        "settings_evasion" to "Anti-censorship",
        "settings_evasion_auto_hint" to "Connects normally, and splits the handshake when a server gets blocked. Starts with what worked for others on your network.",
        "settings_evasion_level" to "Strength",
        "settings_evasion_off_hint" to "Plain connections. Fastest, but easier to block.",
        "settings_evasion_strong" to "Strong",
        "settings_evasion_strong_hint" to "Always disguises traffic. A little slower, much harder to block.",
        "settings_ipv6" to "IPv6 through the tunnel",
        "settings_ipv6_hint" to "Leave off unless your network needs it",
        "settings_iran_direct" to "Iranian sites skip the VPN",
        "settings_iran_direct_hint" to "Iranian sites and banking apps open without the VPN",
        "settings_kill_switch" to "Kill switch",
        "settings_kill_switch_app" to "Block traffic without a server",
        "settings_kill_switch_app_hint" to "While ZeroNet searches, restarts or finds nothing, apps get no internet instead of going out unprotected. ZeroNet keeps retrying until a server works.",
        "settings_kill_switch_body" to "Android's own lock-down also covers the time before ZeroNet starts: in the system VPN settings, open ZeroNet and turn on “Always-on VPN” and “Block connections without VPN”.",
        "settings_kill_switch_open" to "Open VPN settings",
        "settings_language" to "Language",
        "settings_licences" to "Open-source licences",
        "settings_licences_hint" to "ZeroNet is free software under the MIT License",
        "settings_logs" to "Detailed logs",
        "settings_logs_hint" to "Warnings are always kept for Diagnostics; this adds the core's step-by-step detail. Logs stay on this phone.",
        "settings_mode" to "Mode",
        "settings_mode_proxy" to "Proxy only",
        "settings_mode_proxy_hint" to "Only apps you point at the local proxy use it. No VPN icon.",
        "settings_mode_vpn" to "VPN",
        "settings_mode_vpn_hint" to "Every app goes through ZeroNet.",
        "settings_more_connection" to "Kill switch, IPv6, MTU",
        "settings_more_connection_hint" to "Advanced connection options",
        "settings_motion" to "Motion",
        "settings_motion_full" to "Full",
        "settings_motion_full_hint" to "All animations",
        "settings_motion_reduced" to "Reduced",
        "settings_motion_reduced_hint" to "Simple fades only",
        "settings_mtu" to "Packet size (MTU)",
        "settings_mtu_hint" to "%1\$s is fastest. Sites that stall are handled automatically.",
        "settings_no_results" to "No settings match “%1\$s”",
        "settings_palette" to "Theme",
        "settings_palette_dynamic_note" to "Wallpaper colours are on, so the theme only sets the connection colours",
        "settings_preferred_countries" to "Preferred countries",
        "settings_preferred_countries_hint" to "“Fastest” tries these first",
        "settings_privacy" to "Data & privacy",
        "settings_reconnect_now" to "Reconnect now",
        "settings_refresh" to "Refresh lists",
        "settings_refresh_auto" to "Auto",
        "settings_refresh_auto_hint" to "Lists refresh when you connect",
        "settings_refresh_manual" to "Manual",
        "settings_refresh_manual_hint" to "Only when you pull down on the Servers tab",
        "settings_remote_dns" to "DNS for blocked sites",
        "settings_remote_dns_hint" to "Asked through the tunnel, so your ISP can’t see or change the answer",
        "settings_search" to "Search settings",
        "settings_share" to "Share over Wi-Fi",
        "settings_share_address" to "Address on this network",
        "settings_share_auth" to "Password protection",
        "settings_share_auth_hint" to "Optional. Other devices need it to use the proxy.",
        "settings_share_hint" to "Devices on your Wi-Fi or hotspot can use ZeroNet through a proxy",
        "settings_share_http" to "HTTP",
        "settings_share_http_off" to "HTTP sharing is off while a password is set",
        "settings_share_live" to "Sharing now",
        "settings_share_no_network" to "Join a Wi-Fi network or turn on the hotspot to share.",
        "settings_share_pass" to "Password",
        "settings_share_permission_denied" to "Android didn’t allow access to the local network, so sharing stays off.",
        "settings_share_port" to "Port %1\$s",
        "settings_share_qr_description" to "QR code for the proxy at %1\$s",
        "settings_share_qr_hint" to "Scan it on the other device with any proxy app.",
        "settings_share_results" to "Help others connect",
        "settings_share_results_hint" to "Anonymously share which public servers and clean IPs worked on your network, and how well each connection mode did (how fast it connected, how steady it stayed), so others connect faster and the app improves. No addresses, no names, and your own configs are never sent.",
        "settings_share_socks" to "SOCKS5",
        "settings_share_toggle" to "Share this connection",
        "settings_share_user" to "Username",
        "settings_share_when_connected" to "Starts when you connect",
        "settings_sources" to "Server sources",
        "settings_sources_card" to "Servers & sources",
        "settings_sources_value" to "%1\$s of %2\$s public lists on",
        "settings_speed_floor" to "Minimum speed",
        "settings_speed_floor_adaptive" to "Adaptive",
        "settings_speed_floor_adaptive_hint" to "Learns your speed and drops a server that is much slower than your recent ones",
        "settings_speed_floor_custom" to "Custom",
        "settings_speed_floor_custom_hint" to "Speed in kbps",
        "settings_speed_floor_low" to "1 Mbps",
        "settings_speed_floor_low_hint" to "Move off a server under 1 Mbps",
        "settings_speed_floor_medium" to "3 Mbps",
        "settings_speed_floor_medium_hint" to "Move off a server under 3 Mbps",
        "settings_speed_floor_off_hint" to "Switch only when the current server drops",
        "settings_split" to "Split tunnelling",
        "settings_subscriptions" to "Your subscriptions",
        "settings_theme_dark" to "Dark",
        "settings_theme_light" to "Light",
        "settings_theme_mode" to "Light or dark",
        "settings_update_available" to "Version %1\$s is available",
        "settings_update_check" to "Check for updates",
        "settings_update_checking" to "Checking…",
        "settings_update_downloading" to "Downloading… %1\$s",
        "settings_update_failed" to "Couldn't check: %1\$s",
        "settings_update_latest" to "You have the latest version",
        "settings_update_ready" to "Version %1\$s is ready to install",
        "settings_updates" to "Updates",
        "settings_version" to "Version",
        "source_feed" to "Public list · %1\$s",
        "source_public" to "Public list",
        "source_subscription" to "Your subscription",
        "source_user" to "Added by you",
        "sources_add_title" to "Add a subscription",
        "sources_body" to "The public lists ZeroNet searches, and your own subscriptions.",
        "sources_no_subscriptions" to "You haven’t added any yet.",
        "sources_public" to "Public lists",
        "sources_tier_0" to "Tested every two hours; tried first",
        "sources_tier_1" to "Checked on every connect",
        "sources_tier_2" to "Checked when needed",
        "sources_tier_3" to "Checked on a deep search",
        "stage_blocked" to "No working server yet. Traffic is blocked (kill switch) while ZeroNet keeps trying…",
        "stage_chosen_down" to "Your config isn't answering. Trying it again…",
        "stage_connected_pool" to "Backup servers ready: %1\$s",
        "stage_connecting" to "Starting the tunnel…",
        "stage_connecting_to" to "Connecting to %1\$s…",
        "stage_disconnecting" to "Disconnecting…",
        "stage_fetch" to "Getting fresh server lists…",
        "stage_history" to "Trying servers that worked before…",
        "stage_parse" to "Reading %1\$s servers…",
        "stage_real" to "Testing %1\$s servers · %2\$s working",
        "stage_reconnecting" to "Connection dropped. Switching server…",
        "stage_tcp" to "Checking %1\$s servers · %2\$s reachable",
        "state_active" to "Connected now",
        "state_connected_to" to "Connected to %1\$s",
        "state_connecting" to "Connecting",
        "state_disconnected" to "Not connected",
        "stats_download" to "Download",
        "stats_session" to "Session",
        "stats_upload" to "Upload",
        "tab_home" to "Home",
        "tab_scanner" to "Scanner",
        "tab_servers" to "Servers",
        "tab_settings" to "Settings",
        "tile_connected" to "Connected",
        "tile_disconnected" to "Off",
        "tile_searching" to "Searching…",
        "trusted_add" to "Trust this network (%1\$s)",
        "trusted_body" to "ZeroNet stays off on these: it does not connect automatically there, and disconnects when you join one.",
        "trusted_current" to "You are on this network",
        "trusted_none" to "No trusted networks.",
        "trusted_remove" to "Stop trusting %1\$s",
        "trusted_title" to "Trusted networks",
        "trusted_unknown_network" to "This network",
        "unit_b_value" to "%1\$s B",
        "unit_bps" to "bps",
        "unit_gb_value" to "%1\$s GB",
        "unit_gbps" to "Gbps",
        "unit_kb_value" to "%1\$s KB",
        "unit_kbps" to "Kbps",
        "unit_mb_value" to "%1\$s MB",
        "unit_mbps" to "Mbps",
        "update_allow" to "Allow installs",
        "update_allow_hint" to "Android asks once: allow ZeroNet to install apps, then come back and tap Install.",
        "update_cancel" to "Cancel",
        "update_install" to "Install",
        "update_later" to "Later",
        "update_now" to "Update now",
        "update_open_page" to "Open release page",
        "update_progress" to "%1\$s of %2\$s",
        "update_ready_hint" to "Android will ask you to confirm the install.",
        "update_reinstall_body" to "It's signed with a different key than the ZeroNet on this phone, so Android won't install it on top. To get it, uninstall ZeroNet and install the new version from the release page. Your servers and settings will be removed.",
        "update_retry" to "Try again",
        "update_sheet_title" to "Update",
        "update_size" to "%1\$s download. Your servers and settings stay as they are.",
        "update_title_available" to "ZeroNet %1\$s is out",
        "update_title_downloading" to "Downloading %1\$s",
        "update_title_failed" to "The update didn't finish",
        "update_title_ready" to "%1\$s is ready to install",
        "update_title_reinstall" to "This update can't install over your copy",
        "update_whats_new" to "What's new",
        "warp_body" to "Makes a free WARP account. The keys are created on this phone and only their public halves are sent to Cloudflare.",
        "warp_cancel" to "Cancel",
        "warp_done" to "Done. The account was added to your servers.",
        "warp_failed" to "Could not get an account. Check your connection and try again.",
        "warp_fingerprint_note" to "Fingerprint of the new keys",
        "warp_finish" to "Done",
        "warp_get" to "Accept and get account",
        "warp_key_description" to "Fingerprint of the new WARP keys",
        "warp_open" to "Get a Cloudflare WARP account",
        "warp_retry" to "Try again",
        "warp_servers_found" to "%1\$d extra servers found that work through it.",
        "warp_terms" to "This creates an account with Cloudflare. By continuing you accept its terms: cloudflare.com/application/terms",
        "warp_title" to "Cloudflare WARP",
        "warp_working" to "Making the account and looking for servers that work through it…",
        "way_disguise" to "Trying again with the connection disguised…",
        "way_open" to "Trying every remaining method…",
        "way_warp" to "Trying your WARP account…",
        "widget_blocked" to "Blocked — searching",
        "widget_description" to "Connect with one tap and see the server in use",
        "widget_failed" to "Couldn't connect",
        "widget_tap_connect" to "Tap to connect",
        "widget_tap_disconnect" to "Tap to disconnect",
        "widget_toggle" to "Connect or disconnect",
    )
    val FA: Map<String, String> = mapOf(
        "action_add" to "افزودن",
        "action_back" to "بازگشت",
        "action_cancel" to "انصراف",
        "action_clear" to "پاک کردن",
        "action_close" to "بستن",
        "action_collapse" to "پنهان کردن سرورها",
        "action_connect" to "اتصال",
        "action_copy_link" to "کپی لینک",
        "action_copy_value" to "کپی %1\$s",
        "action_delete" to "حذف",
        "action_details" to "جزئیات",
        "action_expand" to "نمایش سرورها",
        "action_favorite" to "افزودن به برگزیده‌ها",
        "action_find_servers" to "پیدا کردن سرور",
        "action_grant_permission" to "اجازه‌ی VPN",
        "action_hide_qr" to "پنهان کردن کد QR",
        "action_paste" to "چسباندن",
        "action_refresh_servers" to "به‌روزرسانی سرورها",
        "action_remove_subscription" to "حذف %1\$s",
        "action_save" to "ذخیره",
        "action_share" to "نمایش کد QR",
        "action_test" to "تست",
        "action_test_servers" to "تست سرورها",
        "action_try_again" to "دوباره امتحان کن",
        "action_unfavorite" to "حذف از برگزیده‌ها",
        "ago_days" to "%1\$s روز پیش",
        "ago_hours" to "%1\$s ساعت پیش",
        "ago_minutes" to "%1\$s دقیقه پیش",
        "ago_never" to "هرگز",
        "ago_now" to "همین حالا",
        "apps_body_except" to "برنامه‌هایی که تیک بزنید از VPN عبور نمی‌کنند.",
        "apps_body_only" to "فقط برنامه‌هایی که تیک بزنید از VPN استفاده می‌کنند.",
        "apps_search" to "جست‌وجوی برنامه",
        "badge_skipped" to "کنار گذاشته",
        "cdn_blocked" to "کانفیگ‌های CDN کلادفلر روی این شبکه کار نمی‌کنند و فعلاً استفاده نمی‌شوند.",
        "cdn_throttled_ech" to "کلادفلر روی این شبکه محدود شده؛ برای عبور، نام سرور پنهان می‌شود.",
        "cdn_throttled_split" to "کلادفلر روی این شبکه محدود شده؛ برای عبور، دست‌دهی تکه‌تکه فرستاده می‌شود.",
        "clear_history_nothing" to "سرور پیدا‌شده‌ای برای پاک کردن نیست.",
        "countries_search" to "جست‌وجوی کشور",
        "country_unknown" to "مکان نامشخص",
        "delay_failed" to "ناموفق",
        "delay_ms" to "⁦%1\$s ms⁩",
        "delay_unknown" to "—",
        "detail_address" to "آدرس",
        "detail_auto_select" to "استفاده در انتخاب خودکار",
        "detail_auto_select_hint" to "خاموش: اتصال و جابه‌جایی خودکار از این سرور رد می‌شود. هنوز می‌توانید با زدن روی آن وصل شوید.",
        "detail_delay" to "تأخیر",
        "detail_delete_confirm" to "این سرور حذف شود؟ این کار برگشت‌پذیر نیست.",
        "detail_error" to "دلیل خطا",
        "detail_history" to "نرخ موفقیت",
        "detail_history_value" to "%1\$s از %2\$s تست",
        "detail_last_tested" to "آخرین تست",
        "detail_protocol" to "پروتکل",
        "detail_qr_description" to "کد QR لینک این سرور",
        "detail_security" to "امنیت",
        "detail_share_warning" to "هر کس این کد را داشته باشد می‌تواند از سرور استفاده کند. فقط با کسانی که به آن‌ها اعتماد دارید به اشتراک بگذارید.",
        "detail_source" to "منبع",
        "detail_testing" to "در حال تست…",
        "detail_transport" to "انتقال",
        "diag_body" to "شبکه‌ی شما را بیرون از تونل بررسی می‌کند، سپس از هر نوع چند سرور ذخیره‌شده را امتحان می‌کند.",
        "diag_dns" to "DNS (سایت‌های فیلترشده)",
        "diag_family" to "سرورها: %1\$s",
        "diag_internet" to "اینترنت ساده",
        "diag_network" to "شبکه",
        "diag_not_run" to "هنوز اجرا نشده.",
        "diag_run" to "شروع آزمایش",
        "diag_run_again" to "آزمایش دوباره",
        "diag_status_bad" to "مسدود",
        "diag_status_ok" to "کار می‌کند",
        "diag_status_pending" to "در انتظار",
        "diag_status_running" to "در حال آزمایش…",
        "diag_status_skipped" to "رد شد",
        "diag_status_warn" to "تا حدی",
        "diag_title" to "آزمایش اتصال",
        "diag_tls" to "نام سرور TLS (DPI)",
        "diag_tunnel" to "از داخل تونل",
        "diag_verdict_families" to "الان این نوع‌ها رد می‌شوند: %1\$s. زیرونت خودکار آن‌ها را ترجیح می‌دهد.",
        "diag_verdict_no_internet" to "این شبکه اصلاً به اینترنت نمی‌رسد و هیچ سروری جواب نداد.",
        "diag_verdict_no_servers" to "هنوز سرور ذخیره‌شده‌ای برای آزمایش نیست. یک بار وصل شوید (یا فهرست سرورها را تازه کنید) و دوباره آزمایش کنید.",
        "diag_verdict_none_work" to "هیچ‌کدام از سرورهای ذخیره‌شده جواب ندادند. فهرست سرورها را تازه کنید، اسکنر آی‌پی تمیز را امتحان کنید یا کانفیگ خودتان را اضافه کنید.",
        "diag_verdict_offline" to "شبکه‌ای وجود ندارد. اول به وای‌فای یا داده‌ی همراه وصل شوید.",
        "fail_core" to "اتصال برقرار نشد. دوباره امتحان کنید.",
        "fail_no_network" to "اینترنت ندارید. وای‌فای یا داده‌ی همراه را بررسی کنید.",
        "fail_no_server" to "روی این اینترنت سرور سالمی پیدا نشد. یک دقیقه‌ی دیگر دوباره امتحان کنید یا ضدسانسور را روی «قوی» بگذارید.",
        "fail_server_unavailable" to "این سرور جواب نمی‌دهد. سریع‌ترین سرور را امتحان کنید.",
        "fail_vpn_permission" to "زیرونت برای ساختن VPN به اجازه‌ی شما نیاز دارد.",
        "fail_vpn_revoked" to "یک VPN دیگر اتصال را گرفت.",
        "gaming_on_note" to "بهترین پینگ، امنیت کمتر: سرورهای ضعیف‌تر و UDP مجاز است.",
        "gaming_on_title" to "حالت گیمینگ روشن شد",
        "gaming_ping" to "پینگ %1\$s ms",
        "gaming_title" to "حالت گیمینگ",
        "import_body" to "یک یا چند لینک کانفیگ، یا لینک اشتراک را اینجا بچسبانید.",
        "import_error" to "وارد نشد: %1\$s",
        "import_links" to "لینک",
        "import_links_placeholder" to "vless://، vmess://، trojan://، ss://…",
        "import_result" to "%1\$s اضافه شد · %2\$s تکراری · %3\$s ناشناخته",
        "import_sub_hint" to "زیرونت آن را همراه فهرست‌های عمومی به‌روز می‌کند.",
        "import_sub_invalid" to "آدرسی وارد کنید که با https:// شروع شود",
        "import_sub_name" to "نام (اختیاری)",
        "import_sub_url" to "https://…",
        "import_subscription" to "اشتراک",
        "import_title" to "افزودن کانفیگ",
        "kind_cdn" to "CDN",
        "kind_crowd" to "برای دیگران کار می‌کند",
        "kind_direct" to "مستقیم",
        "kind_hint_cdn" to "پشت یک CDN مثل کلودفلر: بستن آن بخش بزرگی از وب را می‌بندد.",
        "kind_hint_crowd" to "کاربران دیگر زیرونت گزارش داده‌اند این سرور روی شبکه‌شان کار می‌کند.",
        "kind_hint_direct" to "REALITY: شبیه بازدید از یک سایت واقعی و فیلترنشده است.",
        "kind_hint_other" to "کانفیگ ساده و بدون پوشش: فقط جایی کار می‌کند که هنوز فیلتر نشده.",
        "kind_hint_quic" to "Hysteria2 یا TUIC روی UDP: وقتی UDP باز است سریع است، وگرنه کار نمی‌کند.",
        "kind_hint_split" to "XHTTP با مسیرهای جدا برای ارسال و دریافت: سخت‌ترین نوع برای تشخیص فیلترینگ.",
        "kind_other" to "معمولی",
        "kind_quic" to "QUIC",
        "kind_split" to "مسیر دوتایی",
        "kw_about" to "نسخه مجوز لایسنس کد منبع متن‌باز موتور به‌روزرسانی آپدیت",
        "kw_appearance" to "پوسته رنگ تیره روشن سیاه زبان فارسی انگلیسی انیمیشن حرکت تم",
        "kw_connection" to "وی پی ان پراکسی اتصال خودکار قطع اضطراری همیشه روشن شبکه",
        "kw_diagnostics" to "عیب‌یابی آزمایش مشکل گزارش لاگ وصل نمی‌شود dns dpi",
        "kw_evasion" to "سانسور فیلترینگ فیلترشکن دی ان اس تبلیغات کوییک",
        "kw_privacy" to "گزارش لاگ تاریخچه حذف پاک داده حریم خصوصی اشتراک ناشناس کمک دیگران",
        "kw_share" to "اشتراک هات‌اسپات وای‌فای پراکسی ساکس پورت رمز تترینگ",
        "kw_sources" to "منبع اشتراک ساب لینک فهرست کشور به‌روزرسانی گیت‌هاب",
        "kw_split" to "تونل جداگانه دور زدن برنامه مسیر ایران داخلی شبکه محلی",
        "licences_body" to "زیرونت روی این پروژه‌ها ساخته شده است.",
        "logs_body" to "گزارش اتصال ثبت می‌کند زیرونت چه چیزی را امتحان کرد. برای جزئیات بیشتر از هسته، «گزارش‌های کامل» را در بخش حریم خصوصی روشن کنید.",
        "logs_body_detailed" to "گزارش‌های کامل روشن است. هنگام درخواست کمک این‌ها را بفرستید؛ شامل نام سرورها و خطاهاست، نه سایت‌هایی که باز می‌کنید.",
        "logs_clear" to "پاک کردن",
        "logs_connection" to "اتصال",
        "logs_copy" to "کپی",
        "logs_core" to "هسته",
        "logs_empty" to "هنوز چیزی ثبت نشده.",
        "logs_refresh" to "تازه کردن",
        "logs_share" to "اشتراک",
        "logs_title" to "گزارش‌ها",
        "mars_words" to "در حال اتصال از مریخ، ممکن است کمی طول بکشد",
        "msg_copied" to "کپی شد",
        "msg_deleted" to "سرور حذف شد",
        "msg_history_cleared" to "سرورهای پیدا‌شده پاک شدند",
        "msg_subscription_added" to "اشتراک اضافه شد. در حال گرفتن سرورهایش…",
        "msg_vpn_permission_denied" to "بدون اجازه‌ی VPN نمی‌شود وصل شد",
        "notification_blocked_detail" to "کلید قطع اضطراری: تا پیدا شدن سرور، برنامه‌ها آفلاین‌اند",
        "notification_channel" to "وضعیت اتصال",
        "notification_connected" to "وصل است",
        "notification_connecting" to "در حال اتصال…",
        "notification_disconnect" to "قطع اتصال",
        "notification_reconnecting" to "اتصال دوباره…",
        "notification_searching" to "در حال پیدا کردن سرور…",
        "notification_searching_detail" to "%1\$d بررسی شد · %2\$d سالم",
        "notification_server_ping" to "%1\$s · %2\$d میلیثانیه",
        "notification_switch" to "تعویض سرور",
        "onboarding_allow" to "اجازه دادن",
        "onboarding_later" to "فعلاً نه",
        "onboarding_perm_text" to "دسترسی VPN برای اینکه ترافیک برنامه‌ها از تونل رد شود، و اعلان برای اینکه ببینید وصل هستید یا نه. اندروید هر کدام را فقط یک بار می‌پرسد و بعداً از تنظیمات گوشی می‌توانید عوضشان کنید.",
        "onboarding_perm_title" to "زیرونت به دو دسترسی نیاز دارد",
        "option_auto" to "خودکار",
        "option_off" to "خاموش",
        "option_system" to "پیش‌فرض سیستم",
        "orb_action_connect" to "اتصال",
        "orb_action_disconnect" to "قطع اتصال",
        "orb_connect" to "اتصال",
        "orb_connected" to "وصل است",
        "orb_connecting" to "در حال اتصال",
        "orb_disconnecting" to "در حال قطع",
        "orb_failed" to "دوباره",
        "palette_arctic" to "قطبی",
        "palette_contrast" to "پرکنتراست",
        "palette_golden" to "طلایی",
        "palette_nightshade" to "شبانه",
        "palette_paper" to "کاغذی",
        "palette_sakura" to "ساکورا",
        "path_dns" to "اپراتور شما برای سایت‌های فیلترشده جواب اشتباه می‌دهد.",
        "path_do_dns" to "ZeroNet داخل تونل از DNS خودش استفاده می‌کند، پس این مشکل جلویش را نمی‌گیرد.",
        "path_do_offline" to "به شبکه‌ای که اینترنت دارد وصل شوید و دوباره آزمایش کنید.",
        "path_do_redirect" to "یک بار مرورگر را باز کنید تا صفحهٔ ورود را ببینید، بعد دوباره آزمایش کنید.",
        "path_do_sni" to "ZeroNet سرورهایی را ترجیح می‌دهد که نام را پنهان می‌کنند، پس همچنان رد می‌شوند.",
        "path_filter" to "فیلتر",
        "path_hint_idle" to "آزمایش را اجرا کنید تا ببینید اتصال شما کجا متوقف می‌شود.",
        "path_no_internet" to "این شبکه ترافیک را به اینترنت نمی‌رساند.",
        "path_no_network" to "گوشی شما شبکه ندارد.",
        "path_no_server" to "الان هیچ‌کدام از سرورهای ذخیره‌شده جواب نداد.",
        "path_ok_all" to "الان چیزی جلوی شما را نگرفته است.",
        "path_phone" to "گوشی شما",
        "path_provider" to "اپراتور شما",
        "path_redirected" to "چیزی در این شبکه ترافیک شما را منحرف می‌کند، مثل صفحهٔ ورود یا یک فیلتر.",
        "path_running" to "در حال بررسی هر مرحله از مسیر…",
        "path_sni" to "فیلتر نام سایت را در اتصال‌های امن می‌خواند و آن‌هایی را که نمی‌پسندد قطع می‌کند.",
        "path_world" to "اینترنت آزاد",
        "picker_countries" to "کشورها",
        "picker_empty" to "هنوز سروری نیست. یک بار وصل شوید تا زیرونت چند سرور پیدا کند.",
        "picker_favorites" to "برگزیده‌ها",
        "picker_mine" to "کانفیگ‌های شما",
        "picker_subscriptions" to "اشتراک‌های شما",
        "picker_title" to "انتخاب سرور",
        "profile_fast" to "سریع",
        "profile_fast_hint" to "به اولین سروری که کار کند وصل می‌شود",
        "profile_gaming" to "گیمینگ",
        "profile_gaming_hint" to "بهترین پینگ، امنیت کمتر: سرورهای ضعیف‌تر و UDP مجاز است و وسط بازی سرور عوض نمی‌شود",
        "profile_legacy" to "قدیمی",
        "profile_legacy_hint" to "همان روش قبلی حالت معمولی: سرورهای رمزگذاری‌شده، یک بار جستجو",
        "profile_normal" to "معمولی",
        "profile_normal_hint" to "پیشنهادی. سرورهای رمزگذاری‌شده با پشتیبان، و تا وصل نشود راه‌های دیگر را امتحان می‌کند",
        "profile_tag_fast" to "سریع‌ترین",
        "profile_tag_gaming" to "پینگ کم",
        "profile_tag_legacy" to "کلاسیک",
        "profile_tag_normal" to "پیشنهادی",
        "race_blocked" to "بسته است",
        "race_connected" to "وصل شد · %1\$s ثانیه",
        "race_failed" to "هیچ راهی جواب نداد. شبکهٔ دیگری را امتحان کنید، یا حساب دیگری.",
        "race_failed_short" to "ناموفق",
        "race_h2" to "وب (HTTP/2)",
        "race_h3" to "QUIC (HTTP/3)",
        "race_live" to "در حال امتحان %1\$d راه برای رسیدن به Cloudflare، همزمان…",
        "race_no_answer" to "جواب نداد",
        "race_no_traffic" to "چیزی رد نشد",
        "race_not_needed" to "لازم نشد",
        "race_title" to "چطور وصل شد",
        "race_trying" to "در حال امتحان…",
        "race_waiting" to "منتظر",
        "race_wireguard" to "WireGuard",
        "race_won_blocked" to "از راه %1\$s وصل شد. شبکه راه‌های دیگر را بسته بود، پس برنامه راهی را برداشت که اینجا کار می‌کند.",
        "race_won_fastest" to "از راه %1\$s وصل شد، سریع‌ترین راه در این لحظه.",
        "scan_from_photo" to "از روی عکس",
        "scan_hint" to "دوربین را روی کد QR کانفیگ یا اشتراک بگیرید.",
        "scan_no_camera" to "به دوربین دسترسی نیست. هنوز می‌توانید عکس یا اسکرین‌شات کد را انتخاب کنید.",
        "scan_not_found" to "در این عکس کد QRی پیدا نشد.",
        "scan_qr" to "اسکن کد QR",
        "scanner_again" to "اسکن دوباره",
        "scanner_best" to "بهترین",
        "scanner_copy_best" to "کپی %1\$s تای اول",
        "scanner_copy_ip" to "کپی %1\$s",
        "scanner_done" to "تمام شد",
        "scanner_error_title" to "اسکن متوقف شد",
        "scanner_explainer" to "آدرس‌های کلادفلری را پیدا کنید که هنوز روی شبکه‌ی شما جواب می‌دهند",
        "scanner_how_body" to "خیلی از سرورها پشت کلادفلر هستند. وقتی آی‌پی‌های معمولش فیلتر می‌شوند، یک آی‌پی تمیز که هنوز روی اینترنت شما جواب می‌دهد دوباره راهشان می‌اندازد. زیرونت بهترین نتیجه‌ها را خودش استفاده می‌کند.",
        "scanner_how_title" to "چرا اسکن؟",
        "scanner_idle_hint" to "حدود یک دقیقه",
        "scanner_none_found" to "این بار هیچ آدرسی جواب نداد. بعداً یا روی شبکه‌ی دیگری دوباره امتحان کنید.",
        "scanner_port" to "پورت %1\$s",
        "scanner_progress_description" to "پیشرفت اسکن",
        "scanner_progress_state" to "%1\$s درصد",
        "scanner_ready" to "آماده",
        "scanner_responsive" to "پاسخ‌داده",
        "scanner_results" to "سریع‌ترین آدرس‌ها",
        "scanner_scanned" to "اسکن‌شده",
        "scanner_scanning" to "در حال اسکن…",
        "scanner_start" to "شروع اسکن",
        "scanner_stop" to "توقف",
        "server_card_action" to "انتخاب سرور",
        "server_country_best" to "بهترین سرور این کشور",
        "server_fastest" to "سریع‌ترین سرور",
        "server_fastest_hint" to "زیرونت خودش انتخاب می‌کند",
        "server_fastest_picked" to "سریع‌ترین",
        "server_subscription_hint" to "فقط بین کانفیگ‌های همین اشتراک جابه‌جا می‌شود",
        "servers_add_body" to "لینک کانفیگ یا لینک اشتراک",
        "servers_add_title" to "افزودن کانفیگ",
        "servers_countries" to "کشورها",
        "servers_empty_body" to "روی «پیدا کردن سرور» بزنید. زیرونت فهرست‌های عمومی را می‌گیرد و روی اینترنت شما تستشان می‌کند.",
        "servers_empty_title" to "هنوز سروری ندارید",
        "servers_finding" to "در حال جست‌وجو…",
        "servers_mine" to "مال من",
        "servers_mine_empty_body" to "لینک کانفیگ یا لینک اشتراک را اینجا اضافه کنید.",
        "servers_mine_empty_title" to "هنوز چیزی اضافه نکرده‌اید",
        "servers_no_matches" to "چیزی با «%1\$s» پیدا نشد",
        "servers_rec_empty_body" to "فهرست را تست کنید تا ببینید کدام سرورها روی اینترنت شما کار می‌کنند.",
        "servers_rec_empty_title" to "هنوز سروری تست نشده",
        "servers_recommended" to "پیشنهادی",
        "servers_search" to "جست‌وجوی کشور یا نام",
        "servers_subscriptions" to "اشتراک‌ها",
        "servers_subtitle_empty" to "هنوز چیزی پیدا نشده",
        "servers_testing" to "تست %1\$s از %2\$s…",
        "servers_working_count" to "%1\$s سالم",
        "servers_your_servers" to "کانفیگ‌های شما",
        "settings_about" to "درباره",
        "settings_amoled" to "سیاه خالص",
        "settings_amoled_hint" to "در نمایشگرهای OLED باتری کمتری مصرف می‌کند",
        "settings_anti_sanction" to "DNS برای سرویس‌های تحریمی",
        "settings_anti_sanction_hint" to "سایت‌هایی که IP ایران را مسدود می‌کنند (OpenAI، GitHub، …) از این‌جا پرسیده و مستقیم باز می‌شوند",
        "settings_anti_sanction_note" to "برای استفاده از یکی از گزینه‌های بالا خالی بگذارید. یک IP یا ‏tls://…‎ / ‏https://…/dns-query‎ با نشانی IP پذیرفته می‌شود.",
        "settings_appearance" to "ظاهر",
        "settings_applies_next" to "در اتصال بعدی اعمال می‌شود",
        "settings_apps" to "برنامه‌ها",
        "settings_apps_all" to "همه",
        "settings_apps_except" to "همه جز انتخابی‌ها",
        "settings_apps_none" to "چیزی انتخاب نشده",
        "settings_apps_only" to "فقط انتخابی‌ها",
        "settings_apps_proxy_note" to "فقط در حالت VPN اعمال می‌شود",
        "settings_autoconnect" to "اتصال خودکار",
        "settings_autoconnect_app" to "اجرای برنامه",
        "settings_autoconnect_boot" to "روشن‌شدن گوشی",
        "settings_autoswitch" to "رفتن به سرور سریع‌تر",
        "settings_autoswitch_hint" to "وقتی سرور فعلی کند یا قطع می‌شود",
        "settings_block_ads" to "مسدود کردن تبلیغ و ردیاب",
        "settings_block_ads_hint" to "دامنه‌های تبلیغاتی شناخته‌شده را برای همه‌ی برنامه‌ها فیلتر می‌کند",
        "settings_block_quic" to "مسدود کردن QUIC",
        "settings_block_quic_hint" to "برنامه‌ها به جای گیر کردن، سراغ TCP می‌روند",
        "settings_bypass_lan" to "شبکه‌ی محلی بدون VPN",
        "settings_bypass_lan_hint" to "چاپگر، تلویزیون و مودم در دسترس می‌مانند",
        "settings_choose_apps" to "انتخاب برنامه‌ها",
        "settings_clear_history" to "پاک کردن سرورهای پیدا‌شده",
        "settings_clear_history_hint" to "سرورهای عمومی و نتیجه‌ی تست‌ها فراموش می‌شوند. سرورهای خودتان می‌مانند.",
        "settings_connection" to "اتصال",
        "settings_custom_dns_hint" to "DNS دلخواه (مثلاً ۸.۸.۸.۸)",
        "settings_custom_dns_note" to "برای استفاده از یکی از گزینه‌های بالا خالی بگذارید. یک IP، ‏tls://…‎ یا ‏https://…/dns-query‎ پذیرفته می‌شود.",
        "settings_diag_logs" to "دیدن گزارش‌ها",
        "settings_diag_logs_hint" to "زیرونت چه چیزی را امتحان کرد، چه جواب داد و چرا کار نکرد",
        "settings_diag_test" to "آزمایش اتصال من",
        "settings_diag_test_hint" to "ببینید شبکه‌تان چه چیزی را می‌بندد و کدام نوع سرورها رد می‌شوند",
        "settings_diagnostics" to "عیب‌یابی",
        "settings_dynamic" to "رنگ‌های والپیپر",
        "settings_dynamic_hint" to "رنگ‌های Material You از والپیپر شما",
        "settings_engine" to "موتور",
        "settings_engine_hint" to "هسته‌ی متن‌بازی که اتصال را اجرا می‌کند",
        "settings_evasion" to "ضدسانسور",
        "settings_evasion_auto_hint" to "عادی وصل می‌شود و اگر سروری مسدود شد، دست‌دهی را تکه‌تکه می‌فرستد. از همان روشی شروع می‌کند که برای دیگران روی شبکه‌ی شما جواب داده.",
        "settings_evasion_level" to "شدت",
        "settings_evasion_off_hint" to "اتصال ساده. سریع‌ترین، ولی راحت‌تر مسدود می‌شود.",
        "settings_evasion_strong" to "قوی",
        "settings_evasion_strong_hint" to "ترافیک همیشه پنهان می‌شود. کمی کندتر، ولی خیلی سخت‌تر مسدود می‌شود.",
        "settings_ipv6" to "IPv6 از داخل تونل",
        "settings_ipv6_hint" to "خاموش بماند، مگر شبکه‌تان به آن نیاز داشته باشد",
        "settings_iran_direct" to "سایت‌های ایرانی بدون VPN",
        "settings_iran_direct_hint" to "سایت‌های ایرانی و برنامه‌های بانکی بدون VPN باز می‌شوند",
        "settings_kill_switch" to "کلید قطع اضطراری",
        "settings_kill_switch_app" to "مسدود کردن ترافیک بدون سرور",
        "settings_kill_switch_app_hint" to "وقتی زیرونت در حال جستجو، راه‌اندازی دوباره یا ناموفق است، برنامه‌ها به‌جای خروج بدون محافظت، اینترنت ندارند. زیرونت تا پیدا شدن سرور سالم دوباره تلاش می‌کند.",
        "settings_kill_switch_body" to "قفل خود اندروید زمان پیش از روشن شدن زیرونت را هم پوشش می‌دهد: در تنظیمات VPN سیستم، زیرونت را باز کنید و «VPN همیشه روشن» و «مسدود کردن اتصال‌های بدون VPN» را روشن کنید.",
        "settings_kill_switch_open" to "باز کردن تنظیمات VPN",
        "settings_language" to "زبان",
        "settings_licences" to "مجوزهای متن‌باز",
        "settings_licences_hint" to "زیرونت نرم‌افزار آزاد با مجوز MIT است",
        "settings_logs" to "گزارش‌های کامل",
        "settings_logs_hint" to "هشدارها همیشه برای عیب‌یابی نگه داشته می‌شوند؛ این گزینه جزئیات قدم‌به‌قدم هسته را اضافه می‌کند. گزارش‌ها فقط روی همین گوشی می‌مانند.",
        "settings_mode" to "حالت",
        "settings_mode_proxy" to "فقط پراکسی",
        "settings_mode_proxy_hint" to "فقط برنامه‌هایی که روی پراکسی محلی تنظیم کنید از آن استفاده می‌کنند. آیکن VPN نمایش داده نمی‌شود.",
        "settings_mode_vpn" to "VPN",
        "settings_mode_vpn_hint" to "همه‌ی برنامه‌ها از زیرونت عبور می‌کنند.",
        "settings_more_connection" to "کلید قطع اضطراری، IPv6 و MTU",
        "settings_more_connection_hint" to "گزینه‌های پیشرفته‌ی اتصال",
        "settings_motion" to "حرکت",
        "settings_motion_full" to "کامل",
        "settings_motion_full_hint" to "همه‌ی انیمیشن‌ها",
        "settings_motion_reduced" to "کم",
        "settings_motion_reduced_hint" to "فقط محو شدن ساده",
        "settings_mtu" to "اندازه‌ی بسته (MTU)",
        "settings_mtu_hint" to "%1\$s سریع‌ترین است. سایت‌هایی که گیر می‌کنند خودکار درست می‌شوند.",
        "settings_no_results" to "تنظیمی با «%1\$s» پیدا نشد",
        "settings_palette" to "پوسته",
        "settings_palette_dynamic_note" to "رنگ‌های والپیپر روشن است، پس پوسته فقط رنگ‌های اتصال را تعیین می‌کند",
        "settings_preferred_countries" to "کشورهای ترجیحی",
        "settings_preferred_countries_hint" to "«سریع‌ترین» اول این‌ها را امتحان می‌کند",
        "settings_privacy" to "داده و حریم خصوصی",
        "settings_reconnect_now" to "الان دوباره وصل شو",
        "settings_refresh" to "به‌روزرسانی فهرست‌ها",
        "settings_refresh_auto" to "خودکار",
        "settings_refresh_auto_hint" to "فهرست‌ها هنگام اتصال به‌روز می‌شوند",
        "settings_refresh_manual" to "دستی",
        "settings_refresh_manual_hint" to "فقط وقتی صفحه‌ی سرورها را پایین بکشید",
        "settings_remote_dns" to "DNS برای سایت‌های مسدود",
        "settings_remote_dns_hint" to "از داخل VPN پرسیده می‌شود تا اپراتور نتواند جواب را ببیند یا عوض کند",
        "settings_search" to "جست‌وجو در تنظیمات",
        "settings_share" to "اشتراک روی وای‌فای",
        "settings_share_address" to "آدرس روی این شبکه",
        "settings_share_auth" to "محافظت با رمز",
        "settings_share_auth_hint" to "اختیاری. دستگاه‌های دیگر برای استفاده از پراکسی به آن نیاز دارند.",
        "settings_share_hint" to "دستگاه‌های روی وای‌فای یا هات‌اسپات شما می‌توانند از طریق پراکسی از زیرونت استفاده کنند",
        "settings_share_http" to "HTTP",
        "settings_share_http_off" to "تا وقتی رمز گذاشته شده، اشتراک HTTP خاموش است",
        "settings_share_live" to "در حال اشتراک‌گذاری",
        "settings_share_no_network" to "برای اشتراک‌گذاری به یک وای‌فای وصل شوید یا هات‌اسپات را روشن کنید.",
        "settings_share_pass" to "رمز عبور",
        "settings_share_permission_denied" to "اندروید اجازه‌ی دسترسی به شبکه‌ی محلی را نداد، برای همین اشتراک‌گذاری خاموش ماند.",
        "settings_share_port" to "پورت %1\$s",
        "settings_share_qr_description" to "کد QR پراکسی روی %1\$s",
        "settings_share_qr_hint" to "روی دستگاه دیگر با هر برنامه‌ی پراکسی اسکنش کنید.",
        "settings_share_results" to "کمک به اتصال دیگران",
        "settings_share_results_hint" to "به‌صورت ناشناس اعلام می‌کند کدام سرورهای عمومی و آی‌پی‌های تمیز روی شبکه‌ی شما کار کردند و هر حالت اتصال چقدر خوب عمل کرد (چقدر سریع وصل شد، چقدر پایدار ماند)، تا دیگران سریع‌تر وصل شوند و برنامه بهتر شود. هیچ آدرس یا نامی و هیچ‌کدام از کانفیگ‌های شخصی شما ارسال نمی‌شود.",
        "settings_share_socks" to "SOCKS5",
        "settings_share_toggle" to "اشتراک‌گذاری این اتصال",
        "settings_share_user" to "نام کاربری",
        "settings_share_when_connected" to "با وصل شدن شروع می‌شود",
        "settings_sources" to "منابع سرور",
        "settings_sources_card" to "سرورها و منابع",
        "settings_sources_value" to "%1\$s از %2\$s فهرست عمومی روشن",
        "settings_speed_floor" to "حداقل سرعت",
        "settings_speed_floor_adaptive" to "تطبیقی",
        "settings_speed_floor_adaptive_hint" to "سرعت شما را یاد می‌گیرد و سروری را که خیلی کندتر از سرورهای اخیر است کنار می‌گذارد",
        "settings_speed_floor_custom" to "دلخواه",
        "settings_speed_floor_custom_hint" to "سرعت به کیلوبیت بر ثانیه",
        "settings_speed_floor_low" to "۱ مگابیت",
        "settings_speed_floor_low_hint" to "از سروری زیر ۱ مگابیت بر ثانیه رد شو",
        "settings_speed_floor_medium" to "۳ مگابیت",
        "settings_speed_floor_medium_hint" to "از سروری زیر ۳ مگابیت بر ثانیه رد شو",
        "settings_speed_floor_off_hint" to "فقط وقتی سرور فعلی قطع شود جابه‌جا شو",
        "settings_split" to "تونل جداگانه",
        "settings_subscriptions" to "اشتراک‌های شما",
        "settings_theme_dark" to "تیره",
        "settings_theme_light" to "روشن",
        "settings_theme_mode" to "روشن یا تیره",
        "settings_update_available" to "نسخه‌ی %1\$s آمده است",
        "settings_update_check" to "بررسی به‌روزرسانی",
        "settings_update_checking" to "در حال بررسی…",
        "settings_update_downloading" to "در حال دانلود… %1\$s",
        "settings_update_failed" to "بررسی نشد: %1\$s",
        "settings_update_latest" to "آخرین نسخه را دارید",
        "settings_update_ready" to "نسخه‌ی %1\$s آماده‌ی نصب است",
        "settings_updates" to "به‌روزرسانی",
        "settings_version" to "نسخه",
        "source_feed" to "فهرست عمومی · %1\$s",
        "source_public" to "فهرست عمومی",
        "source_subscription" to "اشتراک شما",
        "source_user" to "افزوده‌ی شما",
        "sources_add_title" to "افزودن اشتراک",
        "sources_body" to "فهرست‌های عمومی‌ای که زیرونت می‌گردد، و اشتراک‌های خودتان.",
        "sources_no_subscriptions" to "هنوز اشتراکی اضافه نکرده‌اید.",
        "sources_public" to "فهرست‌های عمومی",
        "sources_tier_0" to "هر دو ساعت آزمایش می‌شود؛ اول از همه امتحان می‌شود",
        "sources_tier_1" to "در هر اتصال بررسی می‌شود",
        "sources_tier_2" to "در صورت نیاز بررسی می‌شود",
        "sources_tier_3" to "در جست‌وجوی عمیق بررسی می‌شود",
        "stage_blocked" to "هنوز سرور سالمی پیدا نشده. ترافیک مسدود است (کلید قطع اضطراری) و زیرونت همچنان تلاش می‌کند…",
        "stage_chosen_down" to "کانفیگ شما جواب نمی‌دهد. دوباره امتحانش می‌کنیم…",
        "stage_connected_pool" to "سرورهای پشتیبان آماده: %1\$s",
        "stage_connecting" to "راه‌اندازی تونل…",
        "stage_connecting_to" to "اتصال به %1\$s…",
        "stage_disconnecting" to "در حال قطع اتصال…",
        "stage_fetch" to "گرفتن فهرست‌های تازه‌ی سرور…",
        "stage_history" to "امتحان سرورهایی که قبلاً جواب داده‌اند…",
        "stage_parse" to "خواندن %1\$s سرور…",
        "stage_real" to "تست %1\$s سرور · %2\$s سالم",
        "stage_reconnecting" to "اتصال قطع شد. در حال عوض کردن سرور…",
        "stage_tcp" to "بررسی %1\$s سرور · %2\$s در دسترس",
        "state_active" to "الان وصل است",
        "state_connected_to" to "وصل به %1\$s",
        "state_connecting" to "در حال اتصال",
        "state_disconnected" to "وصل نیست",
        "stats_download" to "دانلود",
        "stats_session" to "مدت اتصال",
        "stats_upload" to "آپلود",
        "tab_home" to "خانه",
        "tab_scanner" to "اسکنر",
        "tab_servers" to "سرورها",
        "tab_settings" to "تنظیمات",
        "tile_connected" to "وصل",
        "tile_disconnected" to "خاموش",
        "tile_searching" to "در حال جست‌وجو…",
        "trusted_add" to "اعتماد به این شبکه (%1\$s)",
        "trusted_body" to "زیرونت روی این شبکه‌ها خاموش می‌ماند: خودکار وصل نمی‌شود و با ورود به آن‌ها قطع می‌شود.",
        "trusted_current" to "الان روی همین شبکه هستید",
        "trusted_none" to "هیچ شبکه‌ی مورد اعتمادی نیست.",
        "trusted_remove" to "لغو اعتماد به %1\$s",
        "trusted_title" to "شبکه‌های مورد اعتماد",
        "trusted_unknown_network" to "این شبکه",
        "unit_b_value" to "%1\$s بایت",
        "unit_bps" to "بیت/ث",
        "unit_gb_value" to "%1\$s گیگابایت",
        "unit_gbps" to "گیگابیت/ث",
        "unit_kb_value" to "%1\$s کیلوبایت",
        "unit_kbps" to "کیلوبیت/ث",
        "unit_mb_value" to "%1\$s مگابایت",
        "unit_mbps" to "مگابیت/ث",
        "update_allow" to "اجازه‌ی نصب",
        "update_allow_hint" to "اندروید فقط یک بار می‌پرسد: اجازه‌ی نصب برنامه را به زیرونت بدهید، بعد برگردید و «نصب» را بزنید.",
        "update_cancel" to "لغو",
        "update_install" to "نصب",
        "update_later" to "بعداً",
        "update_now" to "به‌روزرسانی",
        "update_open_page" to "صفحه‌ی انتشار",
        "update_progress" to "%1\$s از %2\$s",
        "update_ready_hint" to "اندروید برای نصب از شما تأیید می‌گیرد.",
        "update_reinstall_body" to "این نسخه با کلیدی متفاوت از زیرونتِ روی گوشی امضا شده، برای همین اندروید آن را روی نسخه‌ی فعلی نصب نمی‌کند. برای گرفتنش، زیرونت را حذف کنید و نسخه‌ی جدید را از صفحه‌ی انتشار نصب کنید. سرورها و تنظیمات شما پاک می‌شوند.",
        "update_retry" to "دوباره",
        "update_sheet_title" to "به‌روزرسانی",
        "update_size" to "حجم دانلود %1\$s. سرورها و تنظیمات شما دست نمی‌خورند.",
        "update_title_available" to "زیرونت %1\$s آمد",
        "update_title_downloading" to "در حال دانلود %1\$s",
        "update_title_failed" to "به‌روزرسانی کامل نشد",
        "update_title_ready" to "%1\$s آماده‌ی نصب است",
        "update_title_reinstall" to "این نسخه روی نسخه‌ی فعلی نصب نمی‌شود",
        "update_whats_new" to "تغییرات",
        "warp_body" to "یک حساب رایگان WARP می‌سازد. کلیدها روی همین گوشی ساخته می‌شوند و فقط نیمهٔ عمومی آن‌ها برای Cloudflare فرستاده می‌شود.",
        "warp_cancel" to "لغو",
        "warp_done" to "انجام شد. حساب به سرورهای شما اضافه شد.",
        "warp_failed" to "حساب گرفته نشد. اتصال خود را بررسی کنید و دوباره تلاش کنید.",
        "warp_fingerprint_note" to "اثر انگشت کلیدهای جدید",
        "warp_finish" to "تمام",
        "warp_get" to "پذیرفتن و گرفتن حساب",
        "warp_key_description" to "اثر انگشت کلیدهای جدید WARP",
        "warp_open" to "گرفتن حساب Cloudflare WARP",
        "warp_retry" to "تلاش دوباره",
        "warp_servers_found" to "%1\$d سرور دیگر پیدا شد که از راه آن کار می‌کنند.",
        "warp_terms" to "این کار یک حساب در Cloudflare می‌سازد. با ادامه دادن، شرایط آن را می‌پذیرید: cloudflare.com/application/terms",
        "warp_title" to "Cloudflare WARP",
        "warp_working" to "در حال ساخت حساب و پیدا کردن سرورهایی که از راه آن کار می‌کنند…",
        "way_disguise" to "دوباره با پنهان‌سازی اتصال امتحان می‌شود…",
        "way_open" to "همهٔ روش‌های باقی‌مانده امتحان می‌شود…",
        "way_warp" to "در حال امتحان حساب WARP شما…",
        "widget_blocked" to "مسدود — در حال جستجو",
        "widget_description" to "با یک لمس وصل شوید و سرور فعلی را ببینید",
        "widget_failed" to "اتصال برقرار نشد",
        "widget_tap_connect" to "برای اتصال بزنید",
        "widget_tap_disconnect" to "برای قطع اتصال بزنید",
        "widget_toggle" to "اتصال یا قطع اتصال",
    )
    val PLURALS_EN: Map<String, Map<String, String>> = mapOf(
        "apps_selected" to mapOf("one" to "%1\$s app", "other" to "%1\$s apps"),
        "clear_history_body" to mapOf("one" to "Forget %1\$s discovered server and its test results? Servers you added stay.", "other" to "Forget %1\$s discovered servers and their test results? Servers you added stay."),
        "servers_count" to mapOf("one" to "%1\$s server", "other" to "%1\$s servers"),
        "servers_subtitle" to mapOf("one" to "%1\$s server · %2\$s working", "other" to "%1\$s servers · %2\$s working"),
        "subscriptions_count" to mapOf("one" to "%1\$s subscription", "other" to "%1\$s subscriptions"),
    )
    val PLURALS_FA: Map<String, Map<String, String>> = mapOf(
        "apps_selected" to mapOf("one" to "%1\$s برنامه", "other" to "%1\$s برنامه"),
        "clear_history_body" to mapOf("one" to "%1\$s سرور پیدا‌شده و نتیجه‌ی تست‌هایش فراموش شود؟ سرورهای خودتان می‌مانند.", "other" to "%1\$s سرور پیدا‌شده و نتیجه‌ی تست‌هایشان فراموش شوند؟ سرورهای خودتان می‌مانند."),
        "servers_count" to mapOf("one" to "%1\$s سرور", "other" to "%1\$s سرور"),
        "servers_subtitle" to mapOf("one" to "%1\$s سرور · %2\$s سالم", "other" to "%1\$s سرور · %2\$s سالم"),
        "subscriptions_count" to mapOf("one" to "%1\$s اشتراک", "other" to "%1\$s اشتراک"),
    )
}

/** The language the UI renders in; synced from Settings. */
object Lang {
    @Volatile var language: AppLanguage = AppLanguage.System

    fun isPersian(): Boolean = when (language) {
        AppLanguage.Persian -> true
        AppLanguage.English -> false
        AppLanguage.System -> Locale.getDefault().language == "fa"
        else -> false
    }

    fun locale(): Locale = if (isPersian()) Locale("fa") else Locale.ENGLISH
}

fun str(id: String, vararg args: Any?): String {
    val table = if (Lang.isPersian()) Strings.FA else Strings.EN
    var s = table[id] ?: Strings.EN[id] ?: id
    if (args.isNotEmpty() || s.contains('%')) {
        s = try { String.format(s, *args) } catch (e: Exception) { s }
    }
    return s
}

fun pluralStr(id: String, count: Int, vararg args: Any?): String {
    val items = (if (Lang.isPersian()) Strings.PLURALS_FA[id] else Strings.PLURALS_EN[id])
        ?: Strings.PLURALS_EN[id]
    val qty = when {
        items == null -> "other"
        !Lang.isPersian() && count == 1 && items.containsKey("one") -> "one"
        items.containsKey("other") -> "other"
        else -> items.keys.first()
    }
    val s = items?.get(qty) ?: id
    return try { String.format(s, *args) } catch (e: Exception) { s }
}

@Composable @ReadOnlyComposable
fun stringResource(id: String, vararg args: Any?): String = str(id, *args)

@Composable @ReadOnlyComposable
fun pluralStringResource(id: String, vararg args: Any?): String = pluralStr(id, (args.firstOrNull() as? Int) ?: 0, *args.drop(1).toTypedArray())

/** A tiny stand-in for android.content.Context: the copied UI only needs getString(). */
class Ctx {
    fun getString(id: String, vararg args: Any?): String = str(id, *args)
    fun getString(id: String, count: Int, vararg args: Any?): String = pluralStr(id, count, *args)
}

val LocalContext = androidx.compose.runtime.staticCompositionLocalOf { Ctx() }
